### ISSUE TITLE
installation instructions didn't work

### ISSUE THREAD

**Issue by marionnewlevant** [craftcms/mandrill#1]
`php composer.phar require craftcms/mandrill` gave me error: "Could not open input file: composer.phar"

`composer require craftcms/mandrill` did work.

**Comment by angrybrad** [comment]
Resolved in https://github.com/craftcms/mandrill/commit/63fc9fc2a361d531c4beafb0316000d25933c540

**Comment by marionnewlevant** [comment]
Similar problem with your other plugin README.md files. I don't want to clutter your github up with issues for all of them.

**Comment by angrybrad** [comment]
Updated the others, too.
