### ISSUE TITLE
Composer 2 warnings

### ISSUE THREAD

**Issue by WHITE-developer** [craftcms/mandrill#4]
While working with composer 1 or 2, we constantly getting warnings.
Checking the mandrill api, it isn't updated since 2015.
Also Mandrill will be renamed to Mailchimp Transactional, so it looks like this is the new api to be used https://github.com/mailchimp/mailchimp-transactional-php

Would be cool if the plugin can be adapted to use the new api which hopefully is working the same but without the composer warnings.
![Screenshot from 2021-02-03 16-19-36](https://user-images.githubusercontent.com/22771556/106771963-d6f0a500-663f-11eb-9359-7c0998d7d582.png)

**Comment by k7y6t5** [comment]
@brandonkelly @angrybrad Can either of you comment on whether this package will be updated to use Transactional Email or if it will be deprecated in favor of a new Transactional Email package?

**Comment by WHITE-developer** [comment]
Composer is now also giving the warning
`Package mandrill/mandrill is abandoned, you should avoid using it. Use mailchimp/transactional instead.`

**Comment by angrybrad** [comment]
We'd need a Swiftmailer compatible version of `mailchimp/transactional,` which, best I can tell, doesn't exist, and the existing library we're using (https://packagist.org/packages/accord/mandrill-swiftmailer) doesn't currently support.

**Comment by brandonkelly** [comment]
We are no longer maintaining this plugin, and recommend you switch to [Mailchimp Transactional](https://plugins.craftcms.com/mailchimp-transactional).
